print(None, type(None))
print(True, type(True))
print(67, type(67))
print(3.6, type(3.6))
print(2+3j, type(2+3j))
print("Hello World", type("Hello World"))
print('Hello World', type('Hello World'))
print(b'Hello', type(b'Hello'))
print(("Hello", 3), type(("Hello", 3)))
print([1,2,3,4], type([1,2,3,4]))
print({'name': 'Tung', 'age': 22}, type({'name': 'Tung', 'age': 22}))